app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from django.conf.urls import url

from . import views

app_name = 'app'

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),
    # The home page
    path('', views.dashboard_page, name='dashboard'),
    path('upload', views.upload_image, name='image_upload'),
    path('images', views.display_image, name='images'),
    path('activities', views.activities_page, name='activities'),
    path('database', views.database_page, name='database'),
    path('test/<slug:slug>/<slug:test_name>', views.test, name='test'),
    path('image/<slug:slug>', views.display_header, name='display_header'),
    path('ct_protocol', views.ct_protocol, name='ct_protocol'),
    path('table_travel', views.table_travel, name='table_travel'),
    path('scout_prescription', views.scout_prescription, name='scout_prescription'),
    path('slice_thickness', views.slice_thickness, name='slice_thickness'),
    path('ct_number_accuracy', views.ct_number_accuracy, name='ct_number_accuracy'),
    path('ct_number_accuracy/<slug:slug>', views.display_mod_one_header, name='display_mod_one_header'),
    path('low_contrast', views.low_contrast, name='low_contrast'),
    path('low_contrast/<slug:slug>', views.display_mod_two_header, name='display_mod_two_header'),
    path('ct_number', views.ct_number, name='ct_number'),
    path('ct_number/<slug:slug>', views.display_mod_three_header, name='display_mod_three_header'),
    path('in_plane', views.in_plane, name='in_plane'),
    path('high_contrast', views.high_contrast, name='high_contrast'),
    path('final_report', views.final_report, name='final_report'),
    path('radiation_beam', views.radiation_beam, name='radiation_beam'),
    path('kvp', views.kvp, name='kvp'),
    path('ct_dosimetry', views.ct_dosimetry, name='ct_dosimetry'),
    path('soft_copy', views.soft_copy, name='soft_copy'),
    path('water_ct', views.water_ct, name='water_ct'),
    path('water_ct/<slug:slug>', views.display_water_header, name='display_water_header'),
    path('technologist_qc', views.technologist_qc, name='technologist_qc'),
    path('technologist_reports', views.technologist_reports, name='technologist_reports'),
    path('technologist_report/<slug:slug>', views.technologist_report, name='technologist_report'),
    path('download_ct_qc_report', views.download_ct_qc_report, name='download_ct_qc_report'),
    path('download_then_dashboard', views.download_then_dashboard, name='download_then_dashboard'),
    path('deleted', views.delete_files, name='delete_files'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts', include('django.contrib.auth.urls')),
    path("", include("authentication.urls")),
    path("", include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/templates/includes/aside-settings.html
    <!-- Custom template | don't include it in your project! -->
    <div class="custom-template">
        <div class="title">Settings</div>
        <div class="custom-content">
            <div class="switcher">
                <div class="switch-block">
                    <h4>Logo Header</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
                        <button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="green"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="red"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="white"></button>
                        <br/>
                        <button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Navbar Header</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeTopBarColor" data-color="dark"></button>
                        <button type="button" class="changeTopBarColor" data-color="blue"></button>
                        <button type="button" class="changeTopBarColor" data-color="purple"></button>
                        <button type="button" class="changeTopBarColor" data-color="light-blue"></button>
                        <button type="button" class="changeTopBarColor" data-color="green"></button>
                        <button type="button" class="changeTopBarColor" data-color="orange"></button>
                        <button type="button" class="changeTopBarColor" data-color="red"></button>
                        <button type="button" class="changeTopBarColor" data-color="white"></button>
                        <br/>
                        <button type="button" class="changeTopBarColor" data-color="dark2"></button>
                        <button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
                        <button type="button" class="changeTopBarColor" data-color="purple2"></button>
                        <button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
                        <button type="button" class="changeTopBarColor" data-color="green2"></button>
                        <button type="button" class="changeTopBarColor" data-color="orange2"></button>
                        <button type="button" class="changeTopBarColor" data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Sidebar</h4>
                    <div class="btnSwitch">
                        <button type="button" class="selected changeSideBarColor" data-color="white"></button>
                        <button type="button" class="changeSideBarColor" data-color="dark"></button>
                        <button type="button" class="changeSideBarColor" data-color="dark2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Background</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeBackgroundColor" data-color="bg2"></button>
                        <button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
                        <button type="button" class="changeBackgroundColor" data-color="bg3"></button>
                        <button type="button" class="changeBackgroundColor" data-color="dark"></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="custom-toggle">
            <i class="flaticon-settings"></i>
        </div>
    </div>
    <!-- End Custom template -->

core/templates/includes/footer.html
  <footer class="footer">
    <div class="container-fluid">
      <div class="copyright ml-auto">
        &copy; Zhou & Associates
      </div>				
    </div>
  </footer>

core/templates/includes/navigation.html
{% load static %}
		<div class="main-header">
			
			<!-- Logo Header -->
			<div class="logo-header" data-background-color="dark2">

				<a href="/" class="logo">
					<img src="{% static 'assets/img/logo.svg' %}" alt="navbar brand" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">
				
				{% if user.is_authenticated %}

					<div class="container-fluid">
						<div class="collapse" id="search-nav">
							<form class="navbar-left navbar-form nav-search mr-md-3">
								<div class="input-group">
									<div class="input-group-prepend">
										<button type="submit" class="btn btn-search pr-1">
											<i class="fa fa-search search-icon"></i>
										</button>
									</div>
									<input type="text" placeholder="Search ..." class="form-control">
								</div>
							</form>
						</div>
						<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
							<li class="nav-item toggle-nav-search hidden-caret">
								<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
									<i class="fa fa-search"></i>
								</a>
							</li>
							<li class="nav-item dropdown hidden-caret">
								<a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fa fa-envelope"></i>
								</a>
								<ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
									<li>
										<div class="dropdown-title d-flex justify-content-between align-items-center">
											Messages 									
											<a href="#" class="small">Mark all as read</a>
										</div>
									</li>
									<li>
										<div class="message-notif-scroll scrollbar-outer">
											<div class="notif-center">
												<a href="#">
													<div class="notif-img"> 
														<img src="{% static 'assets/img/jm_denis.jpg' %}" alt="Img Profile">
													</div>
													<div class="notif-content">
														<span class="subject">Jimmy Denis</span>
														<span class="block">
															How are you ?
														</span>
														<span class="time">5 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-img"> 
														<img src="{% static 'assets/img/chadengle.jpg' %}" alt="Img Profile">
													</div>
													<div class="notif-content">
														<span class="subject">Chad</span>
														<span class="block">
															Ok, Thanks !
														</span>
														<span class="time">12 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-img"> 
														<img src="{% static 'assets/img/mlane.jpg' %}" alt="Img Profile">
													</div>
													<div class="notif-content">
														<span class="subject">Jhon Doe</span>
														<span class="block">
															Ready for the meeting today...
														</span>
														<span class="time">12 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-img"> 
														<img src="{% static 'assets/img/talha.jpg' %}" alt="Img Profile">
													</div>
													<div class="notif-content">
														<span class="subject">Talha</span>
														<span class="block">
															Hi, Apa Kabar ?
														</span>
														<span class="time">17 minutes ago</span> 
													</div>
												</a>
											</div>
										</div>
									</li>
									<li>
										<a class="see-all" href="javascript:void(0);">See all messages<i class="fa fa-angle-right"></i> </a>
									</li>
								</ul>
							</li>
							<li class="nav-item dropdown hidden-caret">
								<a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fa fa-bell"></i>
									<span class="notification">4</span>
								</a>
								<ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
									<li>
										<div class="dropdown-title">You have 4 new notifications</div>
									</li>
									<li>
										<div class="notif-scroll scrollbar-outer">
											<div class="notif-center">
												<a href="#">
													<div class="notif-icon notif-primary"> <i class="fa fa-user-plus"></i> </div>
													<div class="notif-content">
														<span class="block">
															New user registered
														</span>
														<span class="time">5 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-icon notif-success"> <i class="fa fa-comment"></i> </div>
													<div class="notif-content">
														<span class="block">
															Rahmad commented on Admin
														</span>
														<span class="time">12 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-img"> 
														<img src="{% static 'assets/img/profile2.jpg' %}" alt="Img Profile">
													</div>
													<div class="notif-content">
														<span class="block">
															Reza send messages to you
														</span>
														<span class="time">12 minutes ago</span> 
													</div>
												</a>
												<a href="#">
													<div class="notif-icon notif-danger"> <i class="fa fa-heart"></i> </div>
													<div class="notif-content">
														<span class="block">
															Farrah liked Admin
														</span>
														<span class="time">17 minutes ago</span> 
													</div>
												</a>
											</div>
										</div>
									</li>
									<li>
										<a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i> </a>
									</li>
								</ul>
							</li>
							<li class="nav-item dropdown hidden-caret">
								<a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
									<i class="fas fa-layer-group"></i>
								</a>
								<div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
									<div class="quick-actions-header">
										<span class="title mb-1">Quick Actions</span>
										<span class="subtitle op-8">Shortcuts</span>
									</div>
									<div class="quick-actions-scroll scrollbar-outer">
										<div class="quick-actions-items">
											<div class="row m-0">
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-file-1"></i>
														<span class="text">Generated Report</span>
													</div>
												</a>
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-database"></i>
														<span class="text">Create New Database</span>
													</div>
												</a>
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-pen"></i>
														<span class="text">Create New Post</span>
													</div>
												</a>
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-interface-1"></i>
														<span class="text">Create New Task</span>
													</div>
												</a>
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-list"></i>
														<span class="text">Completed Tasks</span>
													</div>
												</a>
												<a class="col-6 col-md-4 p-0" href="#">
													<div class="quick-actions-item">
														<i class="flaticon-file"></i>
														<span class="text">Create New Invoice</span>
													</div>
												</a>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="nav-item dropdown hidden-caret">
								<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
									<div class="avatar-sm">
										<img src="{% static 'assets/img/profile.jpg' %}" alt="..." class="avatar-img rounded-circle">
									</div>
								</a>
								<ul class="dropdown-menu dropdown-user animated fadeIn">
									<div class="dropdown-user-scroll scrollbar-outer">
										<li>
											<div class="user-box">
												<div class="avatar-lg"><img src="{% static 'assets/img/profile.jpg' %}" alt="image profile" class="avatar-img rounded"></div>
												<div class="u-text">
													<h4>
														{{ request.user.username }}
													</h4>
													<p class="text-muted">
														{{ request.user.email }}
													</p>
													
													<a href="#" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
												</div>
											</div>
										</li>
										<li>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href="#">My Profile</a>
											<a class="dropdown-item" href="#">My Balance</a>
											<a class="dropdown-item" href="#">Inbox</a>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item" href={% url 'logout' %}>Logout</a>
										</li>
									</div>
								</ul>
							</li>
						</ul>
					</div>

				{% endif %}
				
			</nav>
			<!-- End Navbar -->

		</div>

core/templates/includes/scripts.html
{% load static %}
	<!--   Core JS Files   -->
	<script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
	<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

	<!-- jQuery UI -->
	<script src="{% static 'assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
	<script src="{% static 'assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>

	<!-- jQuery Scrollbar -->
	<script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

	<!-- Chart JS -->
	<script src="{% static 'assets/js/plugin/chart.js/chart.min.js' %}"></script>

	<!-- jQuery Sparkline -->
	<script src="{% static 'assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

	<!-- Chart Circle -->
	<script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

	<!-- Datatables -->
	<script src="{% static 'assets/js/plugin/datatables/datatables.min.js' %}"></script>

	<!-- Bootstrap Notify -->
	<script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

	<!-- jQuery Vector Maps -->
	<script src="{% static 'assets/js/plugin/jqvmap/jquery.vmap.min.js' %}"></script>
	<script src="{% static 'assets/js/plugin/jqvmap/maps/jquery.vmap.world.js' %}"></script>

	<!-- Sweet Alert -->
	<script src="{% static 'assets/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

	<!-- Atlantis JS -->
	<script src="{% static 'assets/js/atlantis.min.js' %}"></script>

	<script src="{% static 'assets/js/setting-demo.js' %}"></script>

core/templates/includes/sidenav.html
		<!-- Sidebar -->
		<div class="sidebar sidebar-style-2" data-background-color="dark2">
					
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">
						<div class="user">
							<div class="info">
								<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								</a>
								<div class="clearfix"></div>

								<div class="collapse in" id="collapseExample">
									<ul class="nav">
										<li>
											<a href="#profile">
												<span class="link-collapse">My Profile</span>
											</a>
										</li>
										<li>
											<a href={% url 'logout' %}>
												<span class="link-collapse">Logout</span>
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<ul class="nav nav-primary">
							<li class="nav-item active">
									<a href="/">
										<i class="fas fa-home"></i>
										<p>Home</p>
									</a>
							</li>

					{% if user.is_authenticated and request.user|in_group:"medical_physicist" %}

							<li class="nav-item">
								<a data-toggle="collapse" href="#steps">
									<i class="fas fa-pen-square"></i>
									<p>CT Phantom Testing</p>
									<span class="caret"></span>
								</a>
								<div class="collapse" id="steps">
									<ul class="nav nav-collapse">
										<li class="nav-item">
											<a href="ct_protocol_review.html">
												CT Protocol Review
											</a>
										</li>
										<li class="nav-item">
											<a href="table_travel_and_return_to_fixed_position_accuracy.html">
													Table Travel and Return to Fixed Position Accuracy
											</a>
										</li>
										<li class="nav-item">
											<a href="scout_prescription_and_alignment_light_accuracy.html">
													Scout Prescription and Alignment Light Accuracy
											</a>
										</li>
										<li class="nav-item">
											<a href="slice_thickness_accuracy.html">
													Slice Thickness Accuracy
											</a>
										</li>
										<li class="nav-item">
											<a href="in-plane_distance_accuracy.html">
													In-Plane Distance Accuracy
											</a>
										</li>
										<li class="nav-item">
											<a href="radiation_beam_width.html">
													Radiation Beam Width
											</a>
										</li>
										<li class="nav-item">
											<a href="kvp_accuracy_and_hvl_measurement.html">
													kVp Accuracy and HVL Measurement
											</a>
										</li>
										<li class="nav-item">
											<a href="ct_dosimetry.html">
													CT Dosimetry
											</a>
										</li>
										<li class="nav-item">
											<a href="soft-copy_quality_control.html">
													Soft-Copy (Monitor) Quality Control
											</a>
										</li>
										<li class="nav-item">
											<a href="{% url 'app:ct_number_accuracy' %}">
													CT Number Accuracy
											</a>
										</li>
										<li class="nav-item">
											<a href="{% url 'app:low_contrast' %}">
													Low Contrast Performance
											</a>
										</li>
										<li class="nav-item">
											<a href="ct_number_uniformity_and_artifact_evaluation.html">
													CT Number Uniformity and Artifact Evaluation
											</a>
										</li>
										<li class="nav-item">
											<a href="high_contrast_resolution.html">
													High Contrast Resolution
											</a>
										</li>
									</ul>
								</div>
							</li>

							<li class="nav-item">
								<a href="/upload">
									<i class="fas fa-upload"></i>
									<span class="sub-item">Upload Files</span>
								</a>
							</li>
<!--							<li class="nav-item">-->
<!--								<a href="/images">-->
<!--									<i class="fas fa-image"></i>-->
<!--									<span class="sub-item">Images</span>-->
<!--								</a>-->
<!--							</li>-->
							<li class="nav-item">
								<a href="/deleted">
									<i class="fas fa-trash"></i>
									<span class="sub-item">Delete All Files</span>
								</a>
							</li>
							<li style="padding: 0px 28px; color: #b9babf">
								<a><h3 class="sub-item">Data</h3></a>
							</li>
							<li class="nav-item">
								<a href="{% url 'app:activities'%}">
									<i class="fas fa-newspaper"></i>
									<span class="sub-item">Activities</span>
								</a>
							</li>
							<li class="nav-item">
								<a href="{% url 'app:database'%}">
									<i class="fas fa-database"></i>
									<span class="sub-item">Database</span>
								</a>
							</li>
					{% endif %}
					{% if user.is_authenticated and request.user|in_group:"radiology_technician" %}
							<li style="padding: 0px 28px; color: #b9babf">
								<br/>
								<a><h3 class="sub-item">Technologist forms</h3></a>
							</li>
							<li class="nav-item">
								<a href="{% url 'app:technologist_qc' %}">
									<i class="fas fa-calendar"></i>
									<span class="sub-item">Technologist QC</span>
								</a>
							</li>
							<li class="nav-item">
								<a href="{% url 'app:technologist_reports' %}">
									<i class="fas fa-database"></i>
									<span class="sub-item">Technologist QC Reports</span>
								</a>
							</li>
						</ul>
					{% endif %}
				</div>
			</div>
		</div>
		<!-- End Sidebar -->